### ISSUE TITLE
Home screen image scaling issue

### ISSUE THREAD

**Issue by dougproctor** [katiewhite1151/katiewhite1151.github.io#14]
2021.02.18 update - see comment below for remaining issue here. Main contents of the ticket description have been addressed.

Currently on the home screen the full-bleed images occasionally scale such that portions of the image are getting cut off. We should change it so that the images are always displayed at the maximum potential size (e.g. they take up as much room as they can without changing the scale / dimensions). In instances where the browser screen is either very tall or very wide, we should simply allow for more whitespace instead of stretching the image space.

Happy to discuss if the issue or desired outcome are not clear.

A few examples below of how this is showing up as an image currently:

1. Image is cut-off on the sides:
![image](https://user-images.githubusercontent.com/1671916/108104729-e52fbf80-7048-11eb-9c68-dec5581ab107.png)

2. Image is cut-off on the sides:
![image](https://user-images.githubusercontent.com/1671916/108105366-c1b94480-7049-11eb-8230-b070b1bf4e95.png)

3. This looks about right, though note in 4 how the image is cut off when the browser is wide. 
![image](https://user-images.githubusercontent.com/1671916/108104743-e95bdd00-7048-11eb-9ce9-fc37f195bc4e.png)

4. When browser is wide, the image is cut off on the top.
![image](https://user-images.githubusercontent.com/1671916/108105221-946c9680-7049-11eb-964f-7e9a6e015565.png)

**Comment by dougproctor** [comment]
@romakuchukov - looks like you've updated the home screen to avoid the image scaling issue identified above. One other small and related item: currently it looks like the header and footers on the home screen are interfering with a full-bleed layout -- could we please update so that this is not the case (e.g. on home screen, images should go from top of screen to bottom of screen, and header/footer whitespace should not be there).

Ideally the way this will turn out is that images are always full-bleed starting from the right-hand side of the screen, and full bleed on top and bottom. For images that are larger or smaller, this means they will take up more or less of the screen toward the left side of the page (but there should never be whitespace on the top, bottom or righthand side of the screen).

**Comment by romakuchukov** [comment]
So are you ok with the image bleeding outside of the left and bottom corner (see the screenshot). Wouldn't that obscure a part of an image?
![Screen Shot 2021-02-18 at 11 34 40 AM](https://user-images.githubusercontent.com/804157/108389278-8485bb80-71dd-11eb-80b9-7ac7a810034e.JPG)

**Comment by dougproctor** [comment]
@romakuchukov - as it stands, I think you've made some additional changes since I created the original issue above, and I actually think it looks great right now, so don't really need to make further changes here. Ultimately, I think the trick long-term will be for Katie and I to have consistent image dimensions such that we have a consistent gallery on the main page.

That being said, I noticed one minor issue where there's a vertical line to the left of the big red painting -- screenshot below:

![image](https://user-images.githubusercontent.com/1671916/108602613-1a495400-7360-11eb-9138-edd1d21dae50.png)

**Comment by romakuchukov** [comment]
The Line should be gone now.

**Comment by dougproctor** [comment]
Awesome, thanks Roma!
