### ISSUE TITLE
Arrows on "selected works" page should remain in fixed position 

### ISSUE THREAD

**Issue by katiewhite1151** [katiewhite1151/katiewhite1151.github.io#16]
Currently, on the grid view of the "Selected Work" page, the left and right arrows on either side on the image jump up and down as you click through images. This is presumably happening because we are dynamically scaling the height of the image to fit the full-size png on the screen. Instead, we should set a max view height such that we use most of the available visible real-estate, but don't scale the image to be full-size (e.g. avoid needing to scroll). As a consequence, the arrows should remain fixed in one place on the website so they remain constant and unmoving as you click through the images

**Comment by dougproctor** [comment]
Looks like @romakuchukov already knocked this out. Have a few other minor polish items but will create a separate ticket for those.
