### ISSUE TITLE
On "Selected Works" in non-grid view (e.g. single image view), center image vertically on screen and center buttons vertically on image

### ISSUE THREAD

**Issue by dougproctor** [katiewhite1151/katiewhite1151.github.io#17]
Currently on the "Selected Works" screen in single-image view (e.g. not grid view), images are vertically aligned to top of the screen. Instead, we should vertically align center of the screen. 

In addition, buttons should be vertically centered on the image.

Very quick screenshot of the current (w/ arrows to indicate desired) below -- red arrows indicate vertically aligning center the buttons on the image, and blue arrow indicates vertically-aligning-center the image itself.

![image](https://user-images.githubusercontent.com/1671916/108385465-ed166d80-71c8-11eb-84b3-98aa88ed5519.png)

**Comment by romakuchukov** [comment]
should be centered now.

**Comment by dougproctor** [comment]
Yep, looks good. Thanks. Closing
