### ISSUE TITLE
View button is still a bit buggy

### ISSUE THREAD

**Issue by dougproctor** [katiewhite1151/katiewhite1151.github.io#18]
Seeing some weird behavior for the button:

1. Occasionally, clicking the "grid view" button does not shift to the grid view (Screenshot 1)
2. Sometimes, if clicking the "grid view"  toggle is unresponsive, holding shift + clicking works..
3. Noticed that URL occasionally has a `#` at the end, sometimes does not - not sure what's going on here.

Screenshot 1:
![image](https://user-images.githubusercontent.com/1671916/108385672-24851a00-71c9-11eb-9349-6a0f99356c2b.png)

**Comment by romakuchukov** [comment]
Should not be buggy now, but if something similar still happens try recording the steps you took to get to the bug.

**Comment by dougproctor** [comment]
Great, will do. Thanks Roma. I'll close for now and will re-open if I notice any other issues.
