### ISSUE TITLE
In "grid view" > "expanded view" of an image, we should always have a buffer on the top and bottom

### ISSUE THREAD

**Issue by dougproctor** [katiewhite1151/katiewhite1151.github.io#19]
Currently, when selecting the expanded view of an image (from "grid view"), we sometimes have images that are nicely scaled and look great (see screenshot 1), but in other cases, have images that do not have buffer on the top or bottom (which looks a little bit inconsistent and not polished) (screenshot 2). 

Ideally, we should let images be as large as they can be (up to 100% image size) without compromising on image quality, but always have a ~10-20% buffer on the top and bottom of the image. 

screenshot 1 (good scaling)

![image](https://user-images.githubusercontent.com/1671916/108602303-89be4400-735e-11eb-8ee7-18053e4af874.png)

screenshot 2 (no buffer, not great)

![image](https://user-images.githubusercontent.com/1671916/108386166-a37a5280-71c9-11eb-996f-b55089704188.png)

**Comment by romakuchukov** [comment]
The second screenshot is not loading. Can you send it to me separately or reupload it?

**Comment by dougproctor** [comment]
@romakuchukov - updated

**Comment by romakuchukov** [comment]
Added padding. Try it now.

**Comment by dougproctor** [comment]
Confirmed, looks great.
