### ISSUE TITLE
On mobile, make "grid view" a single vertical column

### ISSUE THREAD

**Issue by dougproctor** [katiewhite1151/katiewhite1151.github.io#20]
On mobile "grid view", the images should instead of being a grid simply be a single vertical column. Right now, on a small screen, the grid with three columns looks a bit too small, so a single column should hopefully look cleaner and more polished.

**Comment by romakuchukov** [comment]
I don't think the mobile design is included in Figma.

**Comment by dougproctor** [comment]
Actually, one other thought -- much simpler than what is even there now -- for mobile, can we make the responsive design on the "Selected Works" page such that there is no toggle at all, and we simply have a single, vertical column (with image metadata shown below an image)? I don't think it really is necessary to tap images to expand in mobile.

**Comment by romakuchukov** [comment]
Yeah, I think it's better. I wanted to propose something like this since it simplifies a whole bunch of stuff. Sorry I missed your messages from yesterday.

**Comment by dougproctor** [comment]
Sounds great, thanks Roma - and no worries.

**Comment by romakuchukov** [comment]
Try now. Let me know if it works.

**Comment by dougproctor** [comment]
Looks great, closing
