### ISSUE TITLE
Update left and right arrow buttons

### ISSUE THREAD

**Issue by dougproctor** [katiewhite1151/katiewhite1151.github.io#22]
Please update the left and right arrow buttons on the "Selected works" page with the png's below.

Apologies, meant to include these in the mocks but had forgotten till now.

Thanks
![noun_circle arrow_2989514](https://user-images.githubusercontent.com/1671916/108602268-5b406900-735e-11eb-875a-fed217585fb9.png)
![noun_circle arrow_2989515](https://user-images.githubusercontent.com/1671916/108602271-5bd8ff80-735e-11eb-993c-ff2ed61bd8c9.png)

**Comment by romakuchukov** [comment]
Arrows should be in now.

**Comment by dougproctor** [comment]
Awesome, thanks - just checked and confirmed.
