### ISSUE TITLE
In "grid" view, no longer able to scroll

### ISSUE THREAD

**Issue by dougproctor** [katiewhite1151/katiewhite1151.github.io#23]
@romakuchukov - I added some new images to the selected works section and weirdly I'm no longer able to scroll down on the page... can you please check this out and see if you run into the same issue?

For reference, here's the commit I just made: https://github.com/katiewhite1151/katiewhite1151.github.io/commit/986f3ffcf2e81fc6185d255e7e2c6516e952e6ca

**Comment by romakuchukov** [comment]
Try now.

**Comment by dougproctor** [comment]
Works now!
